-- ==============================================================================
-- RLS POLICIES — generated by backend/sync.sh from policies.json
-- Live snapshot at 2026-07-13T13:51:03Z. Do not hand-edit.
-- Source of truth is the Butterbase platform (manage_rls / butterbase rls list).
-- The *_service_bypass PERMISSIVE ALL policies on every table are omitted here.
-- ==============================================================================

-- activities ----------------------------------------------------------------
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;

CREATE POLICY activities_insert_member ON activities FOR INSERT TO butterbase_user
  WITH CHECK (((actor_user_id = (current_user_id())::uuid) AND (workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid)))));

CREATE POLICY activities_select_member ON activities FOR SELECT TO butterbase_user
  USING ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

-- agent_messages ------------------------------------------------------------
ALTER TABLE agent_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY agent_messages_insert_thread_owner ON agent_messages FOR INSERT TO butterbase_user
  WITH CHECK ((thread_id IN ( SELECT agent_threads.id
   FROM agent_threads
  WHERE (agent_threads.user_id = (current_user_id())::uuid))));

CREATE POLICY agent_messages_select_thread_owner ON agent_messages FOR SELECT TO butterbase_user
  USING ((thread_id IN ( SELECT agent_threads.id
   FROM agent_threads
  WHERE (agent_threads.user_id = (current_user_id())::uuid))));

CREATE POLICY agent_messages_update_thread_owner ON agent_messages FOR UPDATE TO butterbase_user
  USING ((thread_id IN ( SELECT agent_threads.id
   FROM agent_threads
  WHERE (agent_threads.user_id = (current_user_id())::uuid))))
  WITH CHECK ((thread_id IN ( SELECT agent_threads.id
   FROM agent_threads
  WHERE (agent_threads.user_id = (current_user_id())::uuid))));

-- agent_proposals -----------------------------------------------------------
ALTER TABLE agent_proposals ENABLE ROW LEVEL SECURITY;

CREATE POLICY agent_proposals_insert_thread_owner ON agent_proposals FOR INSERT TO butterbase_user
  WITH CHECK (((thread_id IN ( SELECT agent_threads.id
   FROM agent_threads
  WHERE (agent_threads.user_id = (current_user_id())::uuid))) AND (proposed_by = (current_user_id())::uuid) AND (status = 'pending'::text)));

CREATE POLICY agent_proposals_select_thread_owner ON agent_proposals FOR SELECT TO butterbase_user
  USING ((thread_id IN ( SELECT agent_threads.id
   FROM agent_threads
  WHERE (agent_threads.user_id = (current_user_id())::uuid))));

CREATE POLICY agent_proposals_update_thread_owner ON agent_proposals FOR UPDATE TO butterbase_user
  USING (((thread_id IN ( SELECT agent_threads.id
   FROM agent_threads
  WHERE (agent_threads.user_id = (current_user_id())::uuid))) AND (status = 'pending'::text)))
  WITH CHECK (((thread_id IN ( SELECT agent_threads.id
   FROM agent_threads
  WHERE (agent_threads.user_id = (current_user_id())::uuid))) AND (status = ANY (ARRAY['approved'::text, 'rejected'::text]))));

-- agent_threads -------------------------------------------------------------
ALTER TABLE agent_threads ENABLE ROW LEVEL SECURITY;

CREATE POLICY agent_threads_delete_owner ON agent_threads FOR DELETE TO butterbase_user
  USING ((user_id = (current_user_id())::uuid));

CREATE POLICY agent_threads_insert_owner ON agent_threads FOR INSERT TO butterbase_user
  WITH CHECK (((user_id = (current_user_id())::uuid) AND (workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid)))));

CREATE POLICY agent_threads_select_owner ON agent_threads FOR SELECT TO butterbase_user
  USING (((user_id = (current_user_id())::uuid) AND (workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid)))));

CREATE POLICY agent_threads_update_owner ON agent_threads FOR UPDATE TO butterbase_user
  USING ((user_id = (current_user_id())::uuid))
  WITH CHECK ((user_id = (current_user_id())::uuid));

-- app_allowlist -------------------------------------------------------------
ALTER TABLE app_allowlist ENABLE ROW LEVEL SECURITY;

CREATE POLICY app_allowlist_delete_admin ON app_allowlist FOR DELETE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY app_allowlist_insert_admin ON app_allowlist FOR INSERT TO butterbase_user
  WITH CHECK (((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))) AND (created_by = (current_user_id())::uuid)));

CREATE POLICY app_allowlist_insert_bootstrap ON app_allowlist FOR INSERT TO butterbase_user
  WITH CHECK (((NOT (EXISTS ( SELECT 1
   FROM app_allowlist app_allowlist_1))) AND (created_by = (current_user_id())::uuid)));

CREATE POLICY app_allowlist_select_admin ON app_allowlist FOR SELECT TO butterbase_user
  USING ((current_user_id() IS NOT NULL));

CREATE POLICY app_allowlist_update_admin ON app_allowlist FOR UPDATE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

-- attachments ---------------------------------------------------------------
ALTER TABLE attachments ENABLE ROW LEVEL SECURITY;

CREATE POLICY attachments_delete_uploader_or_admin ON attachments FOR DELETE TO butterbase_user
  USING (((uploaded_by = (current_user_id())::uuid) OR (EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = attachments.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));

CREATE POLICY attachments_insert_member ON attachments FOR INSERT TO butterbase_user
  WITH CHECK ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

CREATE POLICY attachments_select_member ON attachments FOR SELECT TO butterbase_user
  USING ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

CREATE POLICY attachments_update_uploader_or_admin ON attachments FOR UPDATE TO butterbase_user
  USING (((uploaded_by = (current_user_id())::uuid) OR (EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = attachments.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text])))))))
  WITH CHECK (((uploaded_by = (current_user_id())::uuid) OR (EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = attachments.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));

-- custom_fields -------------------------------------------------------------
ALTER TABLE custom_fields ENABLE ROW LEVEL SECURITY;

CREATE POLICY custom_fields_all_member ON custom_fields FOR ALL TO butterbase_user
  USING ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))))
  WITH CHECK ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

-- deal_proposals ------------------------------------------------------------
ALTER TABLE deal_proposals ENABLE ROW LEVEL SECURITY;

CREATE POLICY deal_proposals_delete_member ON deal_proposals FOR DELETE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = deal_proposals.workspace_id) AND (m.user_id = (current_user_id())::uuid)))));

CREATE POLICY deal_proposals_select_member ON deal_proposals FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = deal_proposals.workspace_id) AND (m.user_id = (current_user_id())::uuid)))));

CREATE POLICY deal_proposals_update_member ON deal_proposals FOR UPDATE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = deal_proposals.workspace_id) AND (m.user_id = (current_user_id())::uuid)))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = deal_proposals.workspace_id) AND (m.user_id = (current_user_id())::uuid)))));

-- enrichment_settings -------------------------------------------------------
ALTER TABLE enrichment_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY enrichment_settings_upsert_admin ON enrichment_settings FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = enrichment_settings.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = enrichment_settings.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY enrichment_settings_select_member ON enrichment_settings FOR SELECT TO butterbase_user
  USING ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

-- integration_state ---------------------------------------------------------
ALTER TABLE integration_state ENABLE ROW LEVEL SECURITY;

CREATE POLICY integration_state_all_member ON integration_state FOR ALL TO butterbase_user
  USING ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))))
  WITH CHECK ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

-- memberships ---------------------------------------------------------------
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;

CREATE POLICY memberships_delete_admin ON memberships FOR DELETE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = memberships.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY memberships_insert_admin ON memberships FOR INSERT TO butterbase_user
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = memberships.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY memberships_insert_founding_owner ON memberships FOR INSERT TO butterbase_user
  WITH CHECK (((user_id = (current_user_id())::uuid) AND (role = 'owner'::text) AND (EXISTS ( SELECT 1
   FROM workspaces w
  WHERE ((w.id = memberships.workspace_id) AND (w.owner_user_id = (current_user_id())::uuid))))));

CREATE POLICY memberships_select_member ON memberships FOR SELECT TO butterbase_user
  USING ((user_id = (current_user_id())::uuid));

CREATE POLICY memberships_update_admin ON memberships FOR UPDATE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = memberships.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = memberships.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

-- notes ---------------------------------------------------------------------
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY notes_delete_author_or_admin ON notes FOR DELETE TO butterbase_user
  USING (((created_by = (current_user_id())::uuid) OR (EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = notes.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));

CREATE POLICY notes_insert_member ON notes FOR INSERT TO butterbase_user
  WITH CHECK ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

CREATE POLICY notes_select_member ON notes FOR SELECT TO butterbase_user
  USING ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

CREATE POLICY notes_update_author_or_admin ON notes FOR UPDATE TO butterbase_user
  USING (((created_by = (current_user_id())::uuid) OR (EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = notes.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text])))))))
  WITH CHECK (((created_by = (current_user_id())::uuid) OR (EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = notes.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));

-- pending_invites -----------------------------------------------------------
ALTER TABLE pending_invites ENABLE ROW LEVEL SECURITY;

CREATE POLICY pending_invites_delete_admin ON pending_invites FOR DELETE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = pending_invites.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY pending_invites_insert_admin ON pending_invites FOR INSERT TO butterbase_user
  WITH CHECK (((invited_by = (current_user_id())::uuid) AND (EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = pending_invites.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));

CREATE POLICY pending_invites_select_admin ON pending_invites FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = pending_invites.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

-- saved_views ---------------------------------------------------------------
ALTER TABLE saved_views ENABLE ROW LEVEL SECURITY;

CREATE POLICY saved_views_all_member ON saved_views FOR ALL TO butterbase_user
  USING ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))))
  WITH CHECK ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

-- social_post_sends ---------------------------------------------------------
ALTER TABLE social_post_sends ENABLE ROW LEVEL SECURITY;

CREATE POLICY social_post_sends_ws_membership ON social_post_sends FOR ALL TO butterbase_user
  USING ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))))
  WITH CHECK ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

-- social_posts --------------------------------------------------------------
ALTER TABLE social_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY social_posts_ws_membership ON social_posts FOR ALL TO butterbase_user
  USING ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))))
  WITH CHECK ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

-- sync_settings -------------------------------------------------------------
ALTER TABLE sync_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY sync_settings_upsert_admin ON sync_settings FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = sync_settings.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = sync_settings.workspace_id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY sync_settings_select_member ON sync_settings FOR SELECT TO butterbase_user
  USING ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))));

-- workspace_integrations ----------------------------------------------------
ALTER TABLE workspace_integrations ENABLE ROW LEVEL SECURITY;

CREATE POLICY workspace_integrations_all_member ON workspace_integrations FOR ALL TO butterbase_user
  USING ((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))))
  WITH CHECK (((workspace_id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid))) AND (user_id = (current_user_id())::uuid)));

-- workspaces ----------------------------------------------------------------
ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;

CREATE POLICY workspaces_delete_admin ON workspaces FOR DELETE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = workspaces.id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY workspaces_insert_self ON workspaces FOR INSERT TO butterbase_user
  WITH CHECK ((owner_user_id = (current_user_id())::uuid));

CREATE POLICY workspaces_select_member ON workspaces FOR SELECT TO butterbase_user
  USING (((owner_user_id = (current_user_id())::uuid) OR (id IN ( SELECT m.workspace_id
   FROM memberships m
  WHERE (m.user_id = (current_user_id())::uuid)))));

CREATE POLICY workspaces_update_admin ON workspaces FOR UPDATE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = workspaces.id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships m
  WHERE ((m.workspace_id = workspaces.id) AND (m.user_id = (current_user_id())::uuid) AND (m.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

