/**
 * Re-exports the worker handler (for tests) and the `WORKER_SOURCE` constant
 * (for control-api to upload to the WfP dispatch namespace).
 *
 * `WORKER_SOURCE` is populated by ./scripts/emit-source.mjs after `tsc -b`,
 * which reads the compiled `dist/worker.js` and writes a sibling
 * `dist/worker-source.js` exporting it as a string. This file imports from
 * that generated module so consumers get a single clean entry point.
 */
export { default as worker, type Env } from './worker.js';
// eslint-disable-next-line import/no-unresolved -- generated by emit-source.mjs
export { WORKER_SOURCE } from './worker-source.generated.js';
export {
  parseRedirects,
  matchRule,
  findMatchingRule,
  type RedirectRule,
  type ParsedRedirects,
} from './redirects-parser.js';
