// services/control-api/src/services/ctr-front-door.ts
//
// Emits the source for a platform-owned "front door" Worker that is uploaded to
// the bb-containers WfP dispatch namespace for each (app, container) pair.
// No user code is bundled — this is 100% platform-owned. The user's code lives
// in the container image.
//
// Consumers: cloudflare-containers.ts calls buildFrontDoorWorker(cfg) and
// toContainerScriptName(appId, name), and references CTR_CLASS_NAME when
// building the metadata bindings/containers blocks for the CF API upload.

/** The DO class name embedded in every generated Worker. Must match the
 *  `class_name` in the deploy metadata bindings and containers[] blocks. */
export const CTR_CLASS_NAME = 'CtrFrontDoor';

/** Same rule as do-bundler.ts — module-level so it compiles once. */
const VALID_NAME_RE = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;

export interface FrontDoorConfig {
  /** URL-facing container name (kebab-case), e.g. 'game-server'. */
  name: string;
  /** actor: one DO per named key; pool: random slot from 0..maxInstances-1. */
  mode: 'pool' | 'actor';
  /** Who is allowed to call this container endpoint. */
  accessMode: 'public' | 'authenticated' | 'service_key';
  /** TCP port the container process listens on. */
  port: number;
  /** Idle alarm: stop the container after this many seconds of inactivity. */
  sleepAfterS: number;
  /** pool mode only: number of parallel container instances in the pool. */
  maxInstances: number;
}

/** Returns the WfP script name for a given (appId, containerName) pair. */
export function toContainerScriptName(appId: string, name: string): string {
  return `${appId}_ctr_${name}`;
}

/**
 * Emits the full source of the front-door Worker for the given config.
 *
 * The generated Worker:
 *  - Parses /_containers/{name}/{key?}{rest?} and 404s otherwise.
 *  - Enforces access control (public / authenticated / service_key).
 *  - Resolves a DO instance (actor: by key; pool: by random slot).
 *  - Forwards the request to the container via getTcpPort(port).fetch().
 *  - Sets an idle alarm on every request to stop the container after
 *    sleepAfterS seconds of inactivity (belt-and-suspenders: CF also
 *    auto-sleeps idle containers platform-side).
 *
 * Design notes:
 *  - Uses the raw DurableObject form — no `import { Container } from
 *    '@cloudflare/containers'`. That package is NOT bundled into the uploaded
 *    module; the bare ctx.container access pattern is what actually works.
 *  - The container.stop() call in alarm() is wrapped in try/catch and marked
 *    as the to-verify-on-spike-rerun point — the exact stop API is not yet
 *    confirmed against a live CF response. CF auto-sleep makes this non-critical
 *    for correctness, only for cost control.
 */
export function buildFrontDoorWorker(cfg: FrontDoorConfig): string {
  const { name, mode, accessMode, port, sleepAfterS, maxInstances } = cfg;

  if (!VALID_NAME_RE.test(name)) {
    throw new Error(`Invalid container name '${name}': must be lowercase kebab-case`);
  }

  const sleepAfterMs = sleepAfterS * 1000;

  // Bake the route config into a JS const literal (mirrors do-bundler's ROUTES).
  const routeJson = JSON.stringify({ mode, access_mode: accessMode, maxInstances });

  // The URL pattern: /_containers/{name}/{key?}{rest?}
  // Written as a string to avoid template-literal backslash escaping bugs —
  // the JS regex literal is emitted verbatim into the output source.
  const routeRegex = `/^\\/_containers\\/([^/]+)(?:\\/([^/]+))?(\\/.*)?$/`;

  return `\
// Generated by Butterbase CtrFrontDoor builder
// Container: ${name}  mode: ${mode}  access: ${accessMode}  port: ${port}
// DO NOT EDIT — this file is platform-owned and regenerated on each deploy.

const ROUTE = ${routeJson};

async function checkAuth(req, mode) {
  if (mode === 'public') return null;
  const auth = req.headers.get('authorization') || '';
  if (mode === 'service_key') {
    if (!auth.startsWith('Bearer bb_sk_')) {
      return new Response('unauthorized', { status: 401 });
    }
    return null; // Validation against the app's keys is done by an upstream layer.
  }
  // 'authenticated': accept any valid bearer token. Fine-grained validation upstream.
  if (!auth.startsWith('Bearer ')) {
    return new Response('unauthorized', { status: 401 });
  }
  return null;
}

export class ${CTR_CLASS_NAME} {
  constructor(ctx, env) {
    this.ctx = ctx;
    this.env = env;
    this.container = ctx.container;
  }

  async fetch(req) {
    // Race-free: DO fetch is single-threaded per instance, so no concurrent start() call can interleave.
    if (!this.container.running) this.container.start();

    // Re-arm the idle alarm only when stale (avoids one storage write per request).
    const current = await this.ctx.storage.getAlarm();
    if (current === null || current < Date.now() + ${Math.floor(sleepAfterMs / 2)}) {
      await this.ctx.storage.setAlarm(Date.now() + ${sleepAfterMs});
    }

    // The second arg carries method/headers/body from req — do not "simplify" to a manual init or the body is dropped.
    return this.container.getTcpPort(${port}).fetch(req);
  }

  async alarm() {
    if (this.container.running) {
      // NOTE: a quiet-but-open WebSocket past the idle window will be severed here — known M1 limitation;
      // CF auto-sleep has the same behavior.
      // TO-VERIFY-ON-SPIKE-RERUN: container.stop() is the assumed API;
      // confirm exact method name against a live CF response before relying on it.
      try {
        await this.container.stop();
      } catch (_) {
        // Swallow — CF may already have stopped the container.
      }
    }
  }
}

export default {
  async fetch(req, env) {
    const url = new URL(req.url);
    const m = url.pathname.match(${routeRegex});
    if (!m) return new Response('not found', { status: 404 });

    const [, routeName, key, rest] = m;
    if (routeName !== '${name}') return new Response('not found', { status: 404 });

    const denied = await checkAuth(req, ROUTE.access_mode);
    if (denied) return denied;

    let id;
    let innerPath;

    if (ROUTE.mode === 'actor') {
      if (!key) {
        return new Response(
          'actor mode requires a key segment: /_containers/${name}/{key}[/path]',
          { status: 400 },
        );
      }
      id = env.CTR.idFromName(key);
      innerPath = rest || '/';
    } else {
      // pool mode: pick a random slot; the "key" segment (if present) is just path.
      const slot = 'pool-' + Math.floor(Math.random() * ROUTE.maxInstances);
      id = env.CTR.idFromName(slot);
      innerPath = key ? '/' + key + (rest || '') : (rest || '/');
    }

    const inner = new URL(req.url);
    inner.pathname = innerPath;
    // The second arg carries method/headers/body from req — do not "simplify" to a manual init or the body is dropped.
    return env.CTR.get(id).fetch(new Request(inner.toString(), req));
  },
};
`;
}
