/**
 * End-to-end integration tests for dashboard-agent routes.
 *
 * Gate: requires TEST_DATABASE_URL to run (describe.skipIf(!RUN)).
 *
 * External I/O mocked:
 *   - AI gateway:  global.fetch stubbed with hand-crafted OpenAI SSE deltas.
 *   - MCP client:  callMcpTool from mcp-client.ts mocked via vi.mock.
 *
 * Real (not mocked):
 *   - Fastify server booted with dashboardAgentRoutes
 *   - pg.Pool → real Postgres database
 *   - runAgentTurn loop and all store functions
 *
 * Auth: injected via app.addHook('onRequest') — same pattern as people.e2e.test.ts (line 276).
 *
 * Run:
 *   TEST_DATABASE_URL=<postgres-url> pnpm --filter control-api test dashboard-agent.e2e
 */

// Gate: skip the entire suite when no real Postgres is available.
const DB_URL = process.env.TEST_DATABASE_URL;
const RUN = !!DB_URL;

// ── Module mocks (hoisted by Vitest before imports) ──────────────────────────
//
// We mock callMcpTool so the loop never reaches the real MCP server.
// global.fetch is mocked per-test to control gateway SSE responses.

import { vi } from 'vitest';

vi.mock('../../services/dashboard-agent/mcp-client.js', () => ({
  callMcpTool: vi.fn(),
}));

// ── Imports (after mocks) ────────────────────────────────────────────────────

import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import { randomUUID } from 'node:crypto';
import Fastify from 'fastify';
import type { FastifyInstance } from 'fastify';
import pg from 'pg';

import { dashboardAgentRoutes, mergeSnapshotsWithLabels } from '../dashboard-agent.js';
import { callMcpTool } from '../../services/dashboard-agent/mcp-client.js';
import type { SnapshotLabel } from '../../services/dashboard-agent/store.js';
import { appendMessage } from '../../services/dashboard-agent/store.js';
import { createApproval } from '../../services/dashboard-agent/approvals-store.js';

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Build a minimal OpenAI-compatible SSE ReadableStream from delta objects.
 * Appends `data: [DONE]` automatically — matches the gateway wire format.
 */
function makeSseStream(deltas: object[]): ReadableStream<Uint8Array> {
  const encoder = new TextEncoder();
  const body =
    deltas.map((d) => `data: ${JSON.stringify(d)}\n\n`).join('') +
    'data: [DONE]\n\n';
  return new ReadableStream<Uint8Array>({
    start(controller) {
      controller.enqueue(encoder.encode(body));
      controller.close();
    },
  });
}

/** Wrap a delta array in a fake fetch Response with ok:true. */
function gatewayResponse(deltas: object[]): Response {
  return { ok: true, body: makeSseStream(deltas) } as unknown as Response;
}

/**
 * Build a test Fastify app with:
 *   - auth stubbed to userId (null = unauthenticated)
 *   - controlDb decorated with the real pool
 *   - dashboardAgentRoutes registered (no prefix — matches unit test convention)
 *
 * Auth-mock pattern: people.e2e.test.ts lines 275-283.
 */
async function buildApp(userId: string | null, pool: pg.Pool): Promise<FastifyInstance> {
  const app = Fastify({ logger: false });

  app.decorateRequest('auth', null as any);
  app.addHook('onRequest', async (request) => {
    (request as any).auth = {
      userId,
      authMethod: 'jwt' as const,
      scopes: ['*'],
    };
  });

  app.decorate('controlDb', pool as any);
  await app.register(dashboardAgentRoutes);
  await app.ready();
  return app;
}

/** Parse SSE frames emitted by the route (JSON objects in `data: …\n\n` lines). */
function parseSseFrames(body: string): unknown[] {
  return body
    .split('\n\n')
    .filter((segment) => segment.startsWith('data: '))
    .map((segment) => JSON.parse(segment.slice(6)));
}

// ── Unit test: snapshot + label merge helper (no DB / MCP required) ──────────

describe('mergeSnapshotsWithLabels', () => {
  it('merges labels onto matching snapshots and sorts newest-first', () => {
    const rawSnapshots = [
      { snapshot_id: 'snap_1', created_at: '2026-07-01T00:00:00.000Z' },
      { snapshot_id: 'snap_2', created_at: '2026-07-03T00:00:00.000Z' },
      { snapshot_id: 'snap_3', created_at: '2026-07-02T00:00:00.000Z' },
    ];
    const labels: SnapshotLabel[] = [
      {
        snapshotId: 'snap_2',
        label: 'Before redesign',
        autoGenerated: false,
        createdAt: new Date('2026-07-03T00:05:00.000Z'),
      },
    ];

    const merged = mergeSnapshotsWithLabels(rawSnapshots, labels);

    // Newest-first: snap_2 (07-03), snap_3 (07-02), snap_1 (07-01).
    expect(merged.map((s) => s.id)).toEqual(['snap_2', 'snap_3', 'snap_1']);

    const snap2 = merged.find((s) => s.id === 'snap_2');
    expect(snap2).toMatchObject({
      id: 'snap_2',
      label: 'Before redesign',
      auto_generated_label: false,
    });

    const snap1 = merged.find((s) => s.id === 'snap_1');
    expect(snap1).toMatchObject({ id: 'snap_1', label: null, auto_generated_label: false });
  });

  it('defaults message/files_count to null when the source omits them', () => {
    const merged = mergeSnapshotsWithLabels(
      [{ snapshot_id: 'snap_1', created_at: '2026-07-01T00:00:00.000Z' }],
      [],
    );
    expect(merged[0]).toMatchObject({
      id: 'snap_1',
      message: null,
      files_count: null,
      label: null,
      auto_generated_label: false,
    });
  });

  it('marks auto_generated labels correctly', () => {
    const merged = mergeSnapshotsWithLabels(
      [{ snapshot_id: 'snap_1', created_at: '2026-07-01T00:00:00.000Z' }],
      [{ snapshotId: 'snap_1', label: 'Auto: pushed', autoGenerated: true, createdAt: new Date() }],
    );
    expect(merged[0]).toMatchObject({ label: 'Auto: pushed', auto_generated_label: true });
  });
});

// ── Test suite ────────────────────────────────────────────────────────────────

describe.skipIf(!RUN)('dashboard-agent e2e', () => {
  let pool: pg.Pool;

  // Randomised per-run so suites can run concurrently without row collisions.
  const USER_A = randomUUID();
  const USER_B = randomUUID();

  beforeAll(async () => {
    pool = new pg.Pool({ connectionString: DB_URL!, max: 5 });
    process.env.DASHBOARD_ASSISTANT_ENABLED = '1';
  }, 30_000);

  afterAll(async () => {
    delete process.env.DASHBOARD_ASSISTANT_ENABLED;
    if (pool) {
      // Messages cascade-delete with conversations, but be explicit for clarity.
      await pool.query(
        `DELETE FROM dashboard_agent_messages
         WHERE conversation_id IN (
           SELECT id FROM dashboard_agent_conversations WHERE user_id IN ($1, $2)
         )`,
        [USER_A, USER_B],
      );
      await pool.query(
        `DELETE FROM dashboard_agent_conversations WHERE user_id IN ($1, $2)`,
        [USER_A, USER_B],
      );
      await pool.end();
    }
  }, 30_000);

  beforeEach(() => {
    vi.clearAllMocks();
  });

  // ── Case A: SSE frame ordering + DB persistence ───────────────────────────

  describe('Case A: happy path SSE frame ordering', () => {
    it(
      'streams tokens, tool_call, tool_result, then final tokens in order; persists 4 DB rows',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          // ── Step 1: create conversation ──────────────────────────────────────
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-a', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();
          const conversationId = conversation.id;

          // ── Step 2: mock gateway — pass 1 (tokens + tool_call) ──────────────
          //   Emit: token('Hel'), token('lo'), tool_call(c1, manage_app, {action:'list'})
          const pass1 = gatewayResponse([
            { choices: [{ delta: { content: 'Hel' }, finish_reason: null }] },
            { choices: [{ delta: { content: 'lo' }, finish_reason: null }] },
            {
              choices: [
                {
                  delta: {
                    tool_calls: [
                      { index: 0, id: 'c1', function: { name: 'manage_app', arguments: '' } },
                    ],
                  },
                  finish_reason: null,
                },
              ],
            },
            {
              choices: [
                {
                  delta: {
                    tool_calls: [{ index: 0, function: { arguments: '{"action":"list"}' } }],
                  },
                  finish_reason: null,
                },
              ],
            },
            { choices: [{ delta: {}, finish_reason: 'tool_calls' }] },
          ]);

          // ── Step 2: mock gateway — pass 2 (final tokens) ────────────────────
          const pass2 = gatewayResponse([
            { choices: [{ delta: { content: 'You have ' }, finish_reason: null }] },
            { choices: [{ delta: { content: 'no apps.' }, finish_reason: null }] },
            { choices: [{ delta: {}, finish_reason: 'stop' }] },
          ]);

          global.fetch = vi.fn()
            .mockResolvedValueOnce(pass1)
            .mockResolvedValueOnce(pass2);

          // ── Step 3: mock MCP manage_app list → returns {apps:[]} ─────────────
          vi.mocked(callMcpTool).mockResolvedValueOnce({ ok: true, result: { apps: [] } });

          // ── Step 4: POST /messages ───────────────────────────────────────────
          const msgR = await app.inject({
            method: 'POST',
            url: '/messages',
            payload: { conversation_id: conversationId, message: 'do i have apps', model: 'gpt-4o' },
            headers: { authorization: 'Bearer test-jwt' },
          });

          expect(msgR.statusCode).toBe(200);
          expect(msgR.headers['content-type']).toContain('text/event-stream');

          // ── Step 5/6: assert EXACT frame order ───────────────────────────────
          const frames = parseSseFrames(msgR.body);

          expect(frames).toHaveLength(8);
          expect(frames[0]).toMatchObject({ type: 'token', text: 'Hel' });
          expect(frames[1]).toMatchObject({ type: 'token', text: 'lo' });
          expect(frames[2]).toMatchObject({ type: 'tool_call', id: 'c1', name: 'manage_app' });
          expect(frames[3]).toMatchObject({ type: 'tool_result', id: 'c1' });
          expect(frames[4]).toMatchObject({ type: 'token', text: 'You have ' });
          expect(frames[5]).toMatchObject({ type: 'token', text: 'no apps.' });
          expect(frames[6]).toMatchObject({ type: 'assistant_message', content: 'You have no apps.' });
          expect(frames[7]).toMatchObject({ type: 'done' });

          // ── Step 7: verify Postgres rows ─────────────────────────────────────
          type MsgRow = { role: string; content: string; tool_call_id: string | null; tool_result: unknown };
          const { rows } = await pool.query<MsgRow>(
            `SELECT role, content, tool_call_id, tool_result
             FROM dashboard_agent_messages
             WHERE conversation_id = $1
             ORDER BY created_at ASC`,
            [conversationId],
          );

          // Expect exactly 4 rows: user, assistant+toolCall, tool result, final assistant
          expect(rows).toHaveLength(4);

          // Row 1: user message
          expect(rows[0].role).toBe('user');
          expect(rows[0].content).toBe('do i have apps');
          expect(rows[0].tool_call_id).toBeNull();

          // Row 2: assistant row with toolCallId='c1'
          expect(rows[1].role).toBe('assistant');
          expect(rows[1].tool_call_id).toBe('c1');

          // Row 3: tool row with toolCallId='c1' and non-null toolResult
          expect(rows[2].role).toBe('tool');
          expect(rows[2].tool_call_id).toBe('c1');
          expect(rows[2].tool_result).toBeTruthy();

          // Row 4: final assistant row with content, no toolCallId
          expect(rows[3].role).toBe('assistant');
          expect(rows[3].content).toBe('You have no apps.');
          expect(rows[3].tool_call_id).toBeNull();
        } finally {
          await app.close();
        }
      },
      30_000,
    );
  });

  // ── Case B: cross-tenant ownership ────────────────────────────────────────

  describe('Case B: cross-tenant ownership', () => {
    it(
      'returns 404 for all cross-user operations; original conversation survives',
      async () => {
        const appA = await buildApp(USER_A, pool);
        const appB = await buildApp(USER_B, pool);

        try {
          // Step 1: USER_A creates conversation
          const convR = await appA.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-b', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();
          const convA = conversation.id;

          // Step 2: USER_A posts one message (mock a simple no-tool-call pass)
          global.fetch = vi.fn().mockResolvedValueOnce(
            gatewayResponse([
              { choices: [{ delta: { content: 'Hi there.' }, finish_reason: null }] },
              { choices: [{ delta: {}, finish_reason: 'stop' }] },
            ]),
          );

          const msgA = await appA.inject({
            method: 'POST',
            url: '/messages',
            payload: { conversation_id: convA, message: 'hi', model: 'gpt-4o' },
            headers: { authorization: 'Bearer test-jwt-a' },
          });
          expect(msgA.statusCode).toBe(200);

          // Step 3a: USER_B GET /conversations/{conv_a} → 404
          const getR = await appB.inject({
            method: 'GET',
            url: `/conversations/${convA}`,
          });
          expect(getR.statusCode).toBe(404);
          expect(getR.json()).toMatchObject({ error: 'conversation not found' });

          // Step 3b: USER_B DELETE /conversations/{conv_a} → 404 (no-op)
          const delR = await appB.inject({
            method: 'DELETE',
            url: `/conversations/${convA}`,
          });
          expect(delR.statusCode).toBe(404);

          // Step 3c: USER_B POST /messages {conversation_id: convA} → 404
          //          Must be JSON (ownership check fires BEFORE reply.hijack())
          const msgB = await appB.inject({
            method: 'POST',
            url: '/messages',
            payload: { conversation_id: convA, message: 'hi', model: 'gpt-4o' },
            headers: { authorization: 'Bearer test-jwt-b' },
          });
          expect(msgB.statusCode).toBe(404);
          expect(msgB.headers['content-type']).not.toContain('text/event-stream');
          expect(msgB.json()).toMatchObject({ error: 'conversation not found' });

          // Step 4: USER_A can still access their conversation (DELETE was a no-op)
          const ownR = await appA.inject({
            method: 'GET',
            url: `/conversations/${convA}`,
          });
          expect(ownR.statusCode).toBe(200);
        } finally {
          await appA.close();
          await appB.close();
        }
      },
      30_000,
    );
  });

  // ── Case C: feature flag off ───────────────────────────────────────────────

  describe('Case C: feature flag off', () => {
    it(
      'returns 404 on every endpoint when DASHBOARD_ASSISTANT_ENABLED is unset; unauthenticated caller gets 404 not 401',
      async () => {
        // Temporarily unset the flag — restoring in finally so other tests are unaffected.
        delete process.env.DASHBOARD_ASSISTANT_ENABLED;

        // null userId = unauthenticated; flag check must fire before requireUserId
        const app = await buildApp(null, pool);

        try {
          const endpoints: Array<{ method: 'GET' | 'POST' | 'DELETE'; url: string }> = [
            { method: 'POST', url: '/conversations' },
            { method: 'GET', url: '/conversations' },
            { method: 'GET', url: '/conversations/some-id' },
            { method: 'DELETE', url: '/conversations/some-id' },
            { method: 'POST', url: '/messages' },
          ];

          for (const { method, url } of endpoints) {
            const r = await app.inject({ method, url, payload: {} });
            expect(r.statusCode, `${method} ${url} should be 404 when flag is off`).toBe(404);
            expect(r.json()).toMatchObject({ error: 'not enabled' });
          }
        } finally {
          await app.close();
          // Restore flag so subsequent tests in this suite see it as enabled.
          process.env.DASHBOARD_ASSISTANT_ENABLED = '1';
        }
      },
      30_000,
    );
  });

  // ── Case D: rewind endpoint ────────────────────────────────────────────────

  describe('Case D: rewind endpoint', () => {
    const APP_ID = 'app_rewind_test';

    /** Queue the three MCP calls a successful rewind makes, in order. */
    function mockRewindMcpCalls(opts: {
      snapshots: string[];
      pullFiles: Array<{ path: string; sha256: string; download_url: string }>;
      pullSnapshotId: string;
      pushSnapshotId: string;
    }) {
      vi.mocked(callMcpTool)
        // 1. list_snapshots
        .mockResolvedValueOnce({
          ok: true,
          result: { snapshots: opts.snapshots.map((id) => ({ snapshot_id: id, created_at: new Date().toISOString() })) },
        })
        // 2. pull_snapshot
        .mockResolvedValueOnce({
          ok: true,
          result: { snapshot_id: opts.pullSnapshotId, files: opts.pullFiles },
        })
        // 3. push
        .mockResolvedValueOnce({
          ok: true,
          result: { snapshot_id: opts.pushSnapshotId, total_bytes: 1, file_count: opts.pullFiles.length },
        });
    }

    it(
      'requires ownership: user B rewinding user A conversation gets 404',
      async () => {
        const appA = await buildApp(USER_A, pool);
        const appB = await buildApp(USER_B, pool);

        try {
          const convR = await appA.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-d-ownership', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const rewindR = await appB.inject({
            method: 'POST',
            url: `/conversations/${conversation.id}/rewind`,
            payload: { app_id: APP_ID, snapshot_id: 'snap_1' },
            headers: { authorization: 'Bearer test-jwt-b' },
          });

          expect(rewindR.statusCode).toBe(404);
          expect(rewindR.json()).toMatchObject({ error: 'conversation not found' });
          // No MCP calls should have been made — ownership check fires first.
          expect(callMcpTool).not.toHaveBeenCalled();
        } finally {
          await appA.close();
          await appB.close();
        }
      },
      30_000,
    );

    it(
      'rewinds to a valid snapshot: writes an assistant row and returns new_snapshot_id',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-d-happy', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const originalFetch = global.fetch;
          global.fetch = vi.fn().mockResolvedValue(new Response('const x = 1;'));

          mockRewindMcpCalls({
            snapshots: ['snap_1', 'snap_2'],
            pullFiles: [
              { path: 'src/App.tsx', sha256: 'a'.repeat(64), download_url: 'https://s3/a' },
            ],
            pullSnapshotId: 'snap_1',
            pushSnapshotId: 'snap_3',
          });

          try {
            const rewindR = await app.inject({
              method: 'POST',
              url: `/conversations/${conversation.id}/rewind`,
              payload: { app_id: APP_ID, snapshot_id: 'snap_1' },
              headers: { authorization: 'Bearer test-jwt-a' },
            });

            expect(rewindR.statusCode).toBe(200);
            expect(rewindR.json()).toMatchObject({ new_snapshot_id: 'snap_3', files_changed: 1 });

            // callMcpTool called 3x: list_snapshots, pull_snapshot, push
            expect(callMcpTool).toHaveBeenCalledTimes(3);
            expect(vi.mocked(callMcpTool).mock.calls[0][0]).toBe('manage_repo');
            expect((vi.mocked(callMcpTool).mock.calls[0][1] as any).action).toBe('list_snapshots');
            expect((vi.mocked(callMcpTool).mock.calls[1][1] as any).action).toBe('pull_snapshot');
            expect((vi.mocked(callMcpTool).mock.calls[2][1] as any).action).toBe('push');

            // Assistant row persisted recording the rewind.
            type MsgRow = { role: string; content: string; model_used: string | null };
            const { rows } = await pool.query<MsgRow>(
              `SELECT role, content, model_used
               FROM dashboard_agent_messages
               WHERE conversation_id = $1
               ORDER BY created_at ASC`,
              [conversation.id],
            );
            expect(rows).toHaveLength(1);
            expect(rows[0].role).toBe('assistant');
            expect(rows[0].content).toBe('Rewound to snapshot snap_1. Working tree restored.');
            expect(rows[0].model_used).toBeNull();
          } finally {
            global.fetch = originalFetch;
          }
        } finally {
          await app.close();
        }
      },
      30_000,
    );

    it(
      'rejects rewind to a snapshot_id not in the app history with a 4xx and no DB write',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-d-invalid', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          // Only list_snapshots is mocked — snap_999 is not among the returned ids,
          // so the route should reject before ever calling pull_snapshot/push.
          vi.mocked(callMcpTool).mockResolvedValueOnce({
            ok: true,
            result: { snapshots: [{ snapshot_id: 'snap_1', created_at: new Date().toISOString() }] },
          });

          const rewindR = await app.inject({
            method: 'POST',
            url: `/conversations/${conversation.id}/rewind`,
            payload: { app_id: APP_ID, snapshot_id: 'snap_999' },
            headers: { authorization: 'Bearer test-jwt-a' },
          });

          expect(rewindR.statusCode).toBeGreaterThanOrEqual(400);
          expect(rewindR.statusCode).toBeLessThan(500);
          expect(callMcpTool).toHaveBeenCalledTimes(1); // only list_snapshots

          const { rows } = await pool.query(
            `SELECT id FROM dashboard_agent_messages WHERE conversation_id = $1`,
            [conversation.id],
          );
          expect(rows).toHaveLength(0);
        } finally {
          await app.close();
        }
      },
      30_000,
    );
  });

  // ── Case E: snapshot list endpoint ────────────────────────────────────────

  describe('Case E: snapshot list endpoint', () => {
    const APP_ID = 'app_snapshot_list_test';

    it(
      'cross-tenant: user B listing snapshots on user A conversation gets 404',
      async () => {
        const appA = await buildApp(USER_A, pool);
        const appB = await buildApp(USER_B, pool);

        try {
          const convR = await appA.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-e-ownership', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const listR = await appB.inject({
            method: 'GET',
            url: `/conversations/${conversation.id}/snapshots?app_id=${APP_ID}`,
            headers: { authorization: 'Bearer test-jwt-b' },
          });

          expect(listR.statusCode).toBe(404);
          expect(listR.json()).toMatchObject({ error: 'conversation not found' });
          expect(callMcpTool).not.toHaveBeenCalled();
        } finally {
          await appA.close();
          await appB.close();
        }
      },
      30_000,
    );

    it(
      'missing app_id query param returns 400',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-e-missing-app-id', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const listR = await app.inject({
            method: 'GET',
            url: `/conversations/${conversation.id}/snapshots`,
            headers: { authorization: 'Bearer test-jwt-a' },
          });

          expect(listR.statusCode).toBe(400);
          expect(callMcpTool).not.toHaveBeenCalled();
        } finally {
          await app.close();
        }
      },
      30_000,
    );

    it(
      'happy path: merges manage_repo.list_snapshots with a seeded label',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-e-happy', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          // Seed one label for snap_2.
          await pool.query(
            `INSERT INTO dashboard_agent_snapshot_labels
               (conversation_id, app_id, snapshot_id, label, auto_generated)
             VALUES ($1, $2, 'snap_2', 'Checkpoint before rewrite', false)`,
            [conversation.id, APP_ID],
          );

          // Mock manage_repo.list_snapshots to return 2 snapshots.
          vi.mocked(callMcpTool).mockResolvedValueOnce({
            ok: true,
            result: {
              snapshots: [
                { snapshot_id: 'snap_1', created_at: '2026-07-01T00:00:00.000Z' },
                { snapshot_id: 'snap_2', created_at: '2026-07-02T00:00:00.000Z' },
              ],
            },
          });

          const listR = await app.inject({
            method: 'GET',
            url: `/conversations/${conversation.id}/snapshots?app_id=${APP_ID}`,
            headers: { authorization: 'Bearer test-jwt-a' },
          });

          expect(listR.statusCode).toBe(200);
          const { snapshots } = listR.json<{
            snapshots: Array<{
              id: string;
              message: string | null;
              files_count: number | null;
              created_at: string;
              label: string | null;
              auto_generated_label: boolean;
            }>;
          }>();

          expect(snapshots).toHaveLength(2);
          // Newest-first.
          expect(snapshots[0]).toMatchObject({
            id: 'snap_2',
            label: 'Checkpoint before rewrite',
            auto_generated_label: false,
          });
          expect(snapshots[1]).toMatchObject({ id: 'snap_1', label: null, auto_generated_label: false });

          expect(callMcpTool).toHaveBeenCalledTimes(1);
          expect(vi.mocked(callMcpTool).mock.calls[0][0]).toBe('manage_repo');
          expect((vi.mocked(callMcpTool).mock.calls[0][1] as any).action).toBe('list_snapshots');
          expect((vi.mocked(callMcpTool).mock.calls[0][1] as any).app_id).toBe(APP_ID);
        } finally {
          await app.close();
        }
      },
      30_000,
    );
  });

  describe('Case F: label snapshot endpoint', () => {
    const APP_ID = 'app_snapshot_label_test';

    it(
      'cross-tenant: user B labeling a snapshot on user A conversation gets 404',
      async () => {
        const appA = await buildApp(USER_A, pool);
        const appB = await buildApp(USER_B, pool);

        try {
          const convR = await appA.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-f-ownership', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const labelR = await appB.inject({
            method: 'POST',
            url: `/conversations/${conversation.id}/snapshots/label`,
            headers: { authorization: 'Bearer test-jwt-b' },
            payload: { app_id: APP_ID, snapshot_id: 'snap_1', label: 'nope' },
          });

          expect(labelR.statusCode).toBe(404);
          expect(labelR.json()).toMatchObject({ error: 'conversation not found' });
          expect(callMcpTool).not.toHaveBeenCalled();
        } finally {
          await appA.close();
          await appB.close();
        }
      },
      30_000,
    );

    it(
      'happy path: labels a snapshot and it is retrievable via the snapshot list',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-f-happy', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const labelR = await app.inject({
            method: 'POST',
            url: `/conversations/${conversation.id}/snapshots/label`,
            headers: { authorization: 'Bearer test-jwt-a' },
            payload: { app_id: APP_ID, snapshot_id: 'snap_1', label: 'Checkpoint before rewrite' },
          });

          expect(labelR.statusCode).toBe(200);
          expect(labelR.json()).toMatchObject({ ok: true });

          const row = await pool.query(
            `SELECT label, auto_generated FROM dashboard_agent_snapshot_labels
             WHERE conversation_id = $1 AND app_id = $2 AND snapshot_id = 'snap_1'`,
            [conversation.id, APP_ID],
          );
          expect(row.rows).toHaveLength(1);
          expect(row.rows[0]).toMatchObject({ label: 'Checkpoint before rewrite', auto_generated: false });
        } finally {
          await app.close();
        }
      },
      30_000,
    );
  });

  // ── Case G: approvals resolve endpoint ────────────────────────────────────

  describe('Case G: approvals resolve endpoint', () => {
    /**
     * Seed a conversation with a paused assistant tool-call row (as the loop's
     * Plan 3b Task 2 gate would leave it: tool_result=null, pending_approval_id
     * set) plus its matching pending approval row. Mirrors what runAgentTurn
     * does right before it yields `approval_required` and terminates.
     */
    async function seedPendingApproval(convId: string, toolArgs: unknown = { action: 'get_state' }) {
      const toolCallId = `call_${randomUUID()}`;
      const messageId = randomUUID();

      const approval = await createApproval(pool, {
        conversationId: convId,
        turnMessageId: messageId,
        toolName: 'manage_billing',
        toolArgs,
        sensitivity: 'destructive',
      });

      await appendMessage(
        pool,
        convId,
        {
          role: 'assistant',
          content: '',
          toolCallId,
          toolName: 'manage_billing',
          toolArgs,
          toolResult: null,
          modelUsed: 'gpt-4o',
          pendingApprovalId: approval.id,
        },
        messageId,
      );

      return { approval, toolCallId, messageId };
    }

    /** Mock a single-pass resumed-turn gateway response: final tokens, no more tool calls. */
    function mockResumedTurnGateway() {
      global.fetch = vi.fn().mockResolvedValueOnce(
        gatewayResponse([
          { choices: [{ delta: { content: 'Done.' }, finish_reason: null }] },
          { choices: [{ delta: {}, finish_reason: 'stop' }] },
        ]),
      );
    }

    it(
      'cross-tenant approve returns 404',
      async () => {
        const appA = await buildApp(USER_A, pool);
        const appB = await buildApp(USER_B, pool);

        try {
          const convR = await appA.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-g-cross-tenant', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const { approval } = await seedPendingApproval(conversation.id);

          const resolveR = await appB.inject({
            method: 'POST',
            url: `/v1/dashboard-agent/approvals/${approval.id}/resolve`,
            headers: { authorization: 'Bearer test-jwt-b' },
            payload: { status: 'approved' },
          });

          expect(resolveR.statusCode).toBe(404);
          expect(resolveR.headers['content-type']).not.toContain('text/event-stream');
          expect(callMcpTool).not.toHaveBeenCalled();
        } finally {
          await appA.close();
          await appB.close();
        }
      },
      30_000,
    );

    it(
      'resolving an already-resolved approval returns 409',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-g-already-resolved', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const { approval } = await seedPendingApproval(conversation.id);

          // Resolve it once (deny — cheapest path, no MCP call needed).
          mockResumedTurnGateway();
          const first = await app.inject({
            method: 'POST',
            url: `/v1/dashboard-agent/approvals/${approval.id}/resolve`,
            headers: { authorization: 'Bearer test-jwt-a' },
            payload: { status: 'denied' },
          });
          expect(first.statusCode).toBe(200);

          // Second resolve attempt on the now-denied approval → 409.
          const second = await app.inject({
            method: 'POST',
            url: `/v1/dashboard-agent/approvals/${approval.id}/resolve`,
            headers: { authorization: 'Bearer test-jwt-a' },
            payload: { status: 'approved' },
          });
          expect(second.statusCode).toBe(409);
          expect(second.headers['content-type']).not.toContain('text/event-stream');
        } finally {
          await app.close();
        }
      },
      30_000,
    );

    it(
      'approve happy path: executes the tool, persists the tool row, and streams the resumed turn',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-g-approve', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const toolArgs = { action: 'get_state' };
          const { approval, toolCallId } = await seedPendingApproval(conversation.id, toolArgs);

          // The resume helper executes the gated tool via callMcpTool.
          vi.mocked(callMcpTool).mockResolvedValueOnce({ ok: true, result: { balance_cents: 4200 } });
          mockResumedTurnGateway();

          const resolveR = await app.inject({
            method: 'POST',
            url: `/v1/dashboard-agent/approvals/${approval.id}/resolve`,
            headers: { authorization: 'Bearer test-jwt-a' },
            payload: { status: 'approved', trust_scope: 'conversation' },
          });

          expect(resolveR.statusCode).toBe(200);
          expect(resolveR.headers['content-type']).toContain('text/event-stream');

          const frames = parseSseFrames(resolveR.body);
          expect(frames.some((f: any) => f.type === 'assistant_message' || f.type === 'done')).toBe(true);

          // callMcpTool called once (the actual gated execution) — the mocked
          // resumed-turn gateway response has no further tool calls.
          expect(callMcpTool).toHaveBeenCalledTimes(1);
          expect(vi.mocked(callMcpTool).mock.calls[0][0]).toBe('manage_billing');

          // Approval row updated.
          const approvalRow = await pool.query(
            `SELECT status, trust_scope FROM dashboard_agent_approvals WHERE id = $1`,
            [approval.id],
          );
          expect(approvalRow.rows[0]).toMatchObject({ status: 'approved', trust_scope: 'conversation' });

          // Tool-result row persisted with matching tool_call_id and a non-null result.
          const toolRow = await pool.query(
            `SELECT tool_call_id, tool_result, pending_approval_id
             FROM dashboard_agent_messages
             WHERE conversation_id = $1 AND role = 'tool' AND tool_call_id = $2`,
            [conversation.id, toolCallId],
          );
          expect(toolRow.rows).toHaveLength(1);
          expect(toolRow.rows[0].tool_result).toMatchObject({ balance_cents: 4200 });

          // Paused assistant row's pending_approval_id cleared.
          const assistantRow = await pool.query(
            `SELECT pending_approval_id FROM dashboard_agent_messages
             WHERE conversation_id = $1 AND tool_call_id = $2 AND role = 'assistant'`,
            [conversation.id, toolCallId],
          );
          expect(assistantRow.rows[0].pending_approval_id).toBeNull();
        } finally {
          await app.close();
        }
      },
      30_000,
    );

    it(
      'deny happy path: synthesizes a denial tool result including the reason, no MCP execution',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-g-deny', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const { approval, toolCallId } = await seedPendingApproval(conversation.id);

          mockResumedTurnGateway();

          const resolveR = await app.inject({
            method: 'POST',
            url: `/v1/dashboard-agent/approvals/${approval.id}/resolve`,
            headers: { authorization: 'Bearer test-jwt-a' },
            payload: { status: 'denied', reason: 'too risky right now' },
          });

          expect(resolveR.statusCode).toBe(200);
          expect(resolveR.headers['content-type']).toContain('text/event-stream');

          // Denial never calls the MCP client.
          expect(callMcpTool).not.toHaveBeenCalled();

          const approvalRow = await pool.query(
            `SELECT status, deny_reason FROM dashboard_agent_approvals WHERE id = $1`,
            [approval.id],
          );
          expect(approvalRow.rows[0]).toMatchObject({
            status: 'denied',
            deny_reason: 'too risky right now',
          });

          const toolRow = await pool.query(
            `SELECT tool_result FROM dashboard_agent_messages
             WHERE conversation_id = $1 AND role = 'tool' AND tool_call_id = $2`,
            [conversation.id, toolCallId],
          );
          expect(toolRow.rows).toHaveLength(1);
          const result = toolRow.rows[0].tool_result as { ok: boolean; error: string };
          expect(result.ok).toBe(false);
          expect(result.error).toContain('User denied.');
          expect(result.error).toContain('too risky right now');
        } finally {
          await app.close();
        }
      },
      30_000,
    );

    it(
      'approve path MCP failure returns 502, persists no tool row, and leaves the approval pending',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-g-mcp-failure', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const { approval, toolCallId } = await seedPendingApproval(conversation.id);

          // MCP dispatch fails outright (callMcpTool never throws — it
          // resolves to {ok:false, error}).
          vi.mocked(callMcpTool).mockResolvedValueOnce({ ok: false, error: 'mcp down' });

          const resolveR = await app.inject({
            method: 'POST',
            url: `/v1/dashboard-agent/approvals/${approval.id}/resolve`,
            headers: { authorization: 'Bearer test-jwt-a' },
            payload: { status: 'approved' },
          });

          expect(resolveR.statusCode).toBe(502);
          expect(resolveR.headers['content-type']).not.toContain('text/event-stream');
          expect(resolveR.json()).toMatchObject({ error: expect.stringContaining('mcp down') });

          expect(callMcpTool).toHaveBeenCalledTimes(1);

          // Approval was never flipped to 'approved' — tool exec happens
          // before resolveApproval, so a failed exec leaves it pending and
          // retryable.
          const approvalRow = await pool.query(
            `SELECT status FROM dashboard_agent_approvals WHERE id = $1`,
            [approval.id],
          );
          expect(approvalRow.rows[0].status).toBe('pending');

          // No tool-result row was persisted.
          const toolRow = await pool.query(
            `SELECT id FROM dashboard_agent_messages
             WHERE conversation_id = $1 AND role = 'tool' AND tool_call_id = $2`,
            [conversation.id, toolCallId],
          );
          expect(toolRow.rows).toHaveLength(0);

          // Paused assistant row's pending_approval_id is still set (never cleared).
          const assistantRow = await pool.query(
            `SELECT pending_approval_id FROM dashboard_agent_messages
             WHERE conversation_id = $1 AND tool_call_id = $2 AND role = 'assistant'`,
            [conversation.id, toolCallId],
          );
          expect(assistantRow.rows[0].pending_approval_id).toBe(approval.id);
        } finally {
          await app.close();
        }
      },
      30_000,
    );

    it(
      'concurrent double-resolve: exactly one request succeeds, the other gets 409, only one tool row exists',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-g-concurrent', model: 'gpt-4o' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();

          const { approval, toolCallId } = await seedPendingApproval(conversation.id);

          // Both concurrent resolves take the approve path — mock callMcpTool
          // to succeed for whichever request actually reaches it (the loser
          // of the resolveApproval race should never even call it if MCP
          // exec happens first... but tool-exec-first means BOTH requests
          // may call callMcpTool before the DB race is decided. Mock enough
          // responses for both.)
          vi.mocked(callMcpTool).mockResolvedValue({ ok: true, result: { balance_cents: 4200 } });
          mockResumedTurnGateway();
          mockResumedTurnGateway();

          const [first, second] = await Promise.all([
            app.inject({
              method: 'POST',
              url: `/v1/dashboard-agent/approvals/${approval.id}/resolve`,
              headers: { authorization: 'Bearer test-jwt-a' },
              payload: { status: 'approved' },
            }),
            app.inject({
              method: 'POST',
              url: `/v1/dashboard-agent/approvals/${approval.id}/resolve`,
              headers: { authorization: 'Bearer test-jwt-a' },
              payload: { status: 'approved' },
            }),
          ]);

          const codes = [first.statusCode, second.statusCode].sort();
          expect(codes).toEqual([200, 409]);

          const approvalRow = await pool.query(
            `SELECT status FROM dashboard_agent_approvals WHERE id = $1`,
            [approval.id],
          );
          expect(approvalRow.rows[0].status).toBe('approved');

          // Only one tool-result row exists despite both requests potentially
          // calling callMcpTool — the conditional UPDATE ensures only the
          // winner reaches the persist step.
          const toolRows = await pool.query(
            `SELECT id FROM dashboard_agent_messages
             WHERE conversation_id = $1 AND role = 'tool' AND tool_call_id = $2`,
            [conversation.id, toolCallId],
          );
          expect(toolRows.rows).toHaveLength(1);
        } finally {
          await app.close();
        }
      },
      30_000,
    );
  });

  // ── Case H: full pause -> resume smoke (real /messages trigger) ──────────
  //
  // Cases A-G exercise the resolve endpoint against a hand-seeded pending
  // approval. This case drives the WHOLE flow starting from a real user
  // message so the sensitivity gate inside runAgentTurn is what creates the
  // approval — closer to what actually happens in production.

  describe('Case H: full pause -> resume smoke', () => {
    it(
      'manage_app.delete pauses for approval, then approving resumes and executes it',
      async () => {
        const app = await buildApp(USER_A, pool);

        try {
          const convR = await app.inject({
            method: 'POST',
            url: '/conversations',
            payload: { title: 'e2e-case-h-smoke', model: 'anthropic/claude-haiku-4.5' },
          });
          expect(convR.statusCode).toBe(201);
          const { conversation } = convR.json<{ conversation: { id: string } }>();
          const conversationId = conversation.id;

          // ── Phase 1: initial turn — gateway scripts a manage_app.delete call ──
          global.fetch = vi.fn().mockResolvedValueOnce(
            gatewayResponse([
              { choices: [{ delta: { content: 'Sure, deleting it.' }, finish_reason: null }] },
              {
                choices: [
                  {
                    delta: {
                      tool_calls: [
                        { index: 0, id: 'call_del1', function: { name: 'manage_app', arguments: '' } },
                      ],
                    },
                    finish_reason: null,
                  },
                ],
              },
              {
                choices: [
                  {
                    delta: {
                      tool_calls: [
                        { index: 0, function: { arguments: '{"action":"delete","app_id":"app_test"}' } },
                      ],
                    },
                    finish_reason: null,
                  },
                ],
              },
              { choices: [{ delta: {}, finish_reason: 'tool_calls' }] },
            ]),
          );

          const msgR = await app.inject({
            method: 'POST',
            url: '/messages',
            payload: {
              conversation_id: conversationId,
              message: 'delete app app_test',
              model: 'anthropic/claude-haiku-4.5',
            },
            headers: { authorization: 'Bearer test-jwt-a' },
          });

          expect(msgR.statusCode).toBe(200);
          expect(msgR.headers['content-type']).toContain('text/event-stream');

          const initialFrames = parseSseFrames(msgR.body) as Array<{ type: string; [k: string]: unknown }>;

          // MCP must not have been dispatched yet — the gate pauses before exec.
          expect(callMcpTool).not.toHaveBeenCalled();

          const approvalFrame = initialFrames.find((f) => f.type === 'approval_required');
          expect(approvalFrame).toMatchObject({
            type: 'approval_required',
            tool_name: 'manage_app',
            sensitivity: 'destructive',
          });
          expect(typeof approvalFrame?.approval_id).toBe('string');

          // No tool_result and no done frame in this first stream — the turn
          // terminated at the pause, not at a natural end.
          expect(initialFrames.some((f) => f.type === 'tool_result')).toBe(false);
          expect(initialFrames.some((f) => f.type === 'done')).toBe(false);
          expect(initialFrames[initialFrames.length - 1]?.type).toBe('approval_required');

          const approvalId = approvalFrame!.approval_id as string;

          // Pending approval row exists.
          const pendingRow = await pool.query(
            `SELECT status, tool_name, sensitivity FROM dashboard_agent_approvals WHERE id = $1`,
            [approvalId],
          );
          expect(pendingRow.rows).toHaveLength(1);
          expect(pendingRow.rows[0]).toMatchObject({
            status: 'pending',
            tool_name: 'manage_app',
            sensitivity: 'destructive',
          });

          // Assistant row persisted with pending_approval_id set.
          const pausedMsgRow = await pool.query(
            `SELECT role, tool_call_id, pending_approval_id FROM dashboard_agent_messages
             WHERE conversation_id = $1 AND role = 'assistant' AND tool_call_id = 'call_del1'`,
            [conversationId],
          );
          expect(pausedMsgRow.rows).toHaveLength(1);
          expect(pausedMsgRow.rows[0].pending_approval_id).toBe(approvalId);

          // ── Phase 2: approve — resume executes the delete, then wraps up ────
          vi.mocked(callMcpTool).mockResolvedValueOnce({ ok: true, result: { deleted: true } });
          global.fetch = vi.fn().mockResolvedValueOnce(
            gatewayResponse([
              { choices: [{ delta: { content: 'Done. Deleted.' }, finish_reason: null }] },
              { choices: [{ delta: {}, finish_reason: 'stop' }] },
            ]),
          );

          const resolveR = await app.inject({
            method: 'POST',
            url: `/v1/dashboard-agent/approvals/${approvalId}/resolve`,
            headers: { authorization: 'Bearer test-jwt-a' },
            payload: { status: 'approved' },
          });

          expect(resolveR.statusCode).toBe(200);
          expect(resolveR.headers['content-type']).toContain('text/event-stream');

          // The delete exec (via resolveApprovalAndPersistResult) happens
          // BEFORE the resumed runAgentTurn starts, so it's always the first
          // callMcpTool invocation. The resumed turn's own best-effort live
          // schema injection (schema-context.ts) may also call manage_schema
          // for app_test — that's incidental to this smoke test, not the
          // thing under test, so we only assert on the delete call itself.
          const deleteCall = vi
            .mocked(callMcpTool)
            .mock.calls.find(([name, args]) => name === 'manage_app' && (args as any)?.action === 'delete');
          expect(deleteCall).toBeDefined();
          expect(deleteCall?.[1]).toMatchObject({ action: 'delete', app_id: 'app_test' });

          // Note: the executed tool's result is persisted directly to
          // Postgres by resolveApprovalAndPersistResult (see resume.ts)
          // BEFORE the resumed SSE stream even starts — it is not re-emitted
          // as a `tool_result` frame. The resumed stream only carries the
          // NEW gateway pass's events (tokens/assistant_message/done).
          const resumeFrames = parseSseFrames(resolveR.body) as Array<{ type: string; [k: string]: unknown }>;
          expect(resumeFrames.some((f) => f.type === 'tool_result')).toBe(false);
          expect(resumeFrames.some((f) => f.type === 'done' || f.type === 'assistant_message')).toBe(true);

          // Approval flipped to approved.
          const resolvedRow = await pool.query(
            `SELECT status FROM dashboard_agent_approvals WHERE id = $1`,
            [approvalId],
          );
          expect(resolvedRow.rows[0].status).toBe('approved');

          // Tool-role message row persisted for the delete result.
          const toolMsgRow = await pool.query(
            `SELECT role, tool_call_id, tool_result FROM dashboard_agent_messages
             WHERE conversation_id = $1 AND role = 'tool' AND tool_call_id = 'call_del1'`,
            [conversationId],
          );
          expect(toolMsgRow.rows).toHaveLength(1);
          expect(toolMsgRow.rows[0].tool_result).toMatchObject({ deleted: true });
        } finally {
          await app.close();
        }
      },
      30_000,
    );
  });

  // ── Case I: rename / duplicate / pin (Plan 3e Task 5) ─────────────────────

  describe('Case I: rename conversation', () => {
    it('cross-tenant: user B renaming user A conversation gets 404', async () => {
      const appA = await buildApp(USER_A, pool);
      const appB = await buildApp(USER_B, pool);

      try {
        const convR = await appA.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-i-rename-ownership', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();

        const renameR = await appB.inject({
          method: 'PATCH',
          url: `/conversations/${conversation.id}/rename`,
          payload: { title: 'hijacked' },
        });

        expect(renameR.statusCode).toBe(404);
        expect(renameR.json()).toMatchObject({ error: 'conversation not found' });
      } finally {
        await appA.close();
        await appB.close();
      }
    });

    it('happy path: renames the conversation title', async () => {
      const app = await buildApp(USER_A, pool);

      try {
        const convR = await app.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'original title', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();

        const renameR = await app.inject({
          method: 'PATCH',
          url: `/conversations/${conversation.id}/rename`,
          payload: { title: 'renamed title' },
        });

        expect(renameR.statusCode).toBe(200);
        expect(renameR.json()).toMatchObject({ conversation: { title: 'renamed title' } });

        const row = await pool.query(`SELECT title FROM dashboard_agent_conversations WHERE id = $1`, [
          conversation.id,
        ]);
        expect(row.rows[0].title).toBe('renamed title');
      } finally {
        await app.close();
      }
    });

    it('rejects an empty title with 400', async () => {
      const app = await buildApp(USER_A, pool);

      try {
        const convR = await app.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-i-empty-title', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();

        const renameR = await app.inject({
          method: 'PATCH',
          url: `/conversations/${conversation.id}/rename`,
          payload: { title: '' },
        });

        expect(renameR.statusCode).toBe(400);
      } finally {
        await app.close();
      }
    });

    it('rejects a title over 200 chars with 400', async () => {
      const app = await buildApp(USER_A, pool);

      try {
        const convR = await app.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-i-long-title', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();

        const renameR = await app.inject({
          method: 'PATCH',
          url: `/conversations/${conversation.id}/rename`,
          payload: { title: 'x'.repeat(201) },
        });

        expect(renameR.statusCode).toBe(400);
      } finally {
        await app.close();
      }
    });
  });

  describe('Case I: duplicate conversation', () => {
    it('cross-tenant: user B duplicating user A conversation gets 404', async () => {
      const appA = await buildApp(USER_A, pool);
      const appB = await buildApp(USER_B, pool);

      try {
        const convR = await appA.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-i-dup-ownership', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();

        const dupR = await appB.inject({
          method: 'POST',
          url: `/conversations/${conversation.id}/duplicate`,
        });

        expect(dupR.statusCode).toBe(404);
        expect(dupR.json()).toMatchObject({ error: 'conversation not found' });
      } finally {
        await appA.close();
        await appB.close();
      }
    });

    it('happy path: copies the conversation + all messages into a new conversation', async () => {
      const app = await buildApp(USER_A, pool);

      try {
        const convR = await app.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-i-dup-happy', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();

        await appendMessage(pool, conversation.id, {
          role: 'user',
          content: 'hello',
          toolCallId: null,
          toolName: null,
          toolArgs: null,
          toolResult: null,
        });
        await appendMessage(pool, conversation.id, {
          role: 'assistant',
          content: 'hi there',
          toolCallId: null,
          toolName: null,
          toolArgs: null,
          toolResult: null,
        });

        const dupR = await app.inject({
          method: 'POST',
          url: `/conversations/${conversation.id}/duplicate`,
        });

        expect(dupR.statusCode).toBe(201);
        const { conversation: dup } = dupR.json<{ conversation: { id: string; title: string } }>();
        expect(dup.id).not.toBe(conversation.id);
        expect(dup.title).toBe('e2e-case-i-dup-happy (copy)');

        const dupMessages = await pool.query(
          `SELECT role, content FROM dashboard_agent_messages WHERE conversation_id = $1 ORDER BY created_at ASC`,
          [dup.id],
        );
        expect(dupMessages.rows).toHaveLength(2);
        expect(dupMessages.rows[0]).toMatchObject({ role: 'user', content: 'hello' });
        expect(dupMessages.rows[1]).toMatchObject({ role: 'assistant', content: 'hi there' });

        // Deleting the original does not affect the copy (cascade preserved).
        const delR = await app.inject({ method: 'DELETE', url: `/conversations/${conversation.id}` });
        expect(delR.statusCode).toBe(204);

        const stillThere = await pool.query(`SELECT id FROM dashboard_agent_conversations WHERE id = $1`, [
          dup.id,
        ]);
        expect(stillThere.rows).toHaveLength(1);

        const dupMessagesAfter = await pool.query(
          `SELECT id FROM dashboard_agent_messages WHERE conversation_id = $1`,
          [dup.id],
        );
        expect(dupMessagesAfter.rows).toHaveLength(2);
      } finally {
        await app.close();
      }
    });
  });

  describe('Case I: pin conversation', () => {
    it('cross-tenant: user B pinning user A conversation gets 404', async () => {
      const appA = await buildApp(USER_A, pool);
      const appB = await buildApp(USER_B, pool);

      try {
        const convR = await appA.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-i-pin-ownership', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();

        const pinR = await appB.inject({
          method: 'POST',
          url: `/conversations/${conversation.id}/pin`,
          payload: { pinned: true },
        });

        expect(pinR.statusCode).toBe(404);
        expect(pinR.json()).toMatchObject({ error: 'conversation not found' });
      } finally {
        await appA.close();
        await appB.close();
      }
    });

    it('happy path: toggles pinned_at set then cleared', async () => {
      const app = await buildApp(USER_A, pool);

      try {
        const convR = await app.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-i-pin-toggle', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();

        const pinR = await app.inject({
          method: 'POST',
          url: `/conversations/${conversation.id}/pin`,
          payload: { pinned: true },
        });
        expect(pinR.statusCode).toBe(200);
        expect(pinR.json<{ conversation: { pinnedAt: string | null } }>().conversation.pinnedAt).not.toBeNull();

        const pinnedRow = await pool.query(
          `SELECT pinned_at FROM dashboard_agent_conversations WHERE id = $1`,
          [conversation.id],
        );
        expect(pinnedRow.rows[0].pinned_at).not.toBeNull();

        const unpinR = await app.inject({
          method: 'POST',
          url: `/conversations/${conversation.id}/pin`,
          payload: { pinned: false },
        });
        expect(unpinR.statusCode).toBe(200);
        expect(unpinR.json<{ conversation: { pinnedAt: string | null } }>().conversation.pinnedAt).toBeNull();

        const unpinnedRow = await pool.query(
          `SELECT pinned_at FROM dashboard_agent_conversations WHERE id = $1`,
          [conversation.id],
        );
        expect(unpinnedRow.rows[0].pinned_at).toBeNull();
      } finally {
        await app.close();
      }
    });

    it('listConversations returns pinned conversations first', async () => {
      const app = await buildApp(USER_A, pool);

      try {
        const convR1 = await app.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-i-list-1', model: 'gpt-4o' },
        });
        const conv1 = convR1.json<{ conversation: { id: string } }>().conversation;

        const convR2 = await app.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-i-list-2', model: 'gpt-4o' },
        });
        const conv2 = convR2.json<{ conversation: { id: string } }>().conversation;

        // Pin the SECOND (older-created) conversation — it should still sort
        // first despite conv1 being newer, because pinned_at wins.
        const pinR = await app.inject({
          method: 'POST',
          url: `/conversations/${conv2.id}/pin`,
          payload: { pinned: true },
        });
        expect(pinR.statusCode).toBe(200);

        const listR = await app.inject({ method: 'GET', url: '/conversations' });
        expect(listR.statusCode).toBe(200);
        const { conversations } = listR.json<{ conversations: Array<{ id: string }> }>();

        const ids = conversations.map((c) => c.id);
        const idx1 = ids.indexOf(conv1.id);
        const idx2 = ids.indexOf(conv2.id);
        expect(idx2).toBeGreaterThanOrEqual(0);
        expect(idx1).toBeGreaterThanOrEqual(0);
        expect(idx2).toBeLessThan(idx1);
      } finally {
        await app.close();
      }
    });
  });

  // ── Case J: regenerate / edit-and-resend ──────────────────────────────────

  describe('Case J: regenerate', () => {
    it('cross-tenant: user B regenerating from user A conversation gets 404', async () => {
      const appA = await buildApp(USER_A, pool);
      const appB = await buildApp(USER_B, pool);

      try {
        const convR = await appA.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-j-regen-ownership', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();

        const userMsg = await appendMessage(pool, conversation.id, {
          role: 'user',
          content: 'hi',
          toolCallId: null,
          toolName: null,
          toolArgs: null,
          toolResult: null,
        });
        const asstMsg = await appendMessage(pool, conversation.id, {
          role: 'assistant',
          content: 'hello there',
          toolCallId: null,
          toolName: null,
          toolArgs: null,
          toolResult: null,
        });

        const regenR = await appB.inject({
          method: 'POST',
          url: `/conversations/${conversation.id}/regenerate`,
          payload: { message_id: asstMsg.id },
          headers: { authorization: 'Bearer test-jwt' },
        });

        expect(regenR.statusCode).toBe(404);
        expect(regenR.json()).toMatchObject({ error: 'conversation not found' });

        // Original messages survive untouched.
        const rows = await pool.query(
          `SELECT id FROM dashboard_agent_messages WHERE conversation_id = $1`,
          [conversation.id],
        );
        expect(rows.rows.map((r) => r.id).sort()).toEqual([userMsg.id, asstMsg.id].sort());
      } finally {
        await appA.close();
        await appB.close();
      }
    });

    it('happy path: deletes the assistant message + everything after, streams a new turn', async () => {
      const app = await buildApp(USER_A, pool);

      try {
        const convR = await app.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-j-regen-happy', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();
        const conversationId = conversation.id;

        const userMsg = await appendMessage(pool, conversationId, {
          role: 'user',
          content: 'do i have apps',
          toolCallId: null,
          toolName: null,
          toolArgs: null,
          toolResult: null,
        });
        const asstMsg = await appendMessage(pool, conversationId, {
          role: 'assistant',
          content: 'You have no apps.',
          toolCallId: null,
          toolName: null,
          toolArgs: null,
          toolResult: null,
        });
        // A stray follow-up row after the assistant message (simulates a
        // subsequent turn) — must also be deleted since it's >= the target.
        const strayMsg = await appendMessage(pool, conversationId, {
          role: 'user',
          content: 'stray follow-up',
          toolCallId: null,
          toolName: null,
          toolArgs: null,
          toolResult: null,
        });

        global.fetch = vi.fn().mockResolvedValueOnce(
          gatewayResponse([
            { choices: [{ delta: { content: 'You still have ' }, finish_reason: null }] },
            { choices: [{ delta: { content: 'no apps.' }, finish_reason: null }] },
            { choices: [{ delta: {}, finish_reason: 'stop' }] },
          ]),
        );

        const regenR = await app.inject({
          method: 'POST',
          url: `/conversations/${conversationId}/regenerate`,
          payload: { message_id: asstMsg.id },
          headers: { authorization: 'Bearer test-jwt' },
        });

        expect(regenR.statusCode).toBe(200);
        expect(regenR.headers['content-type']).toContain('text/event-stream');

        const frames = parseSseFrames(regenR.body);
        expect(frames.some((f) => (f as { type: string }).type === 'assistant_message')).toBe(true);
        expect(frames[frames.length - 1]).toMatchObject({ type: 'done' });

        // Original assistant message + stray follow-up are gone; the user
        // message survives (it's before the deletion point) and is replayed.
        const rows = await pool.query<{ id: string; role: string; content: string }>(
          `SELECT id, role, content FROM dashboard_agent_messages
           WHERE conversation_id = $1 ORDER BY created_at ASC`,
          [conversationId],
        );
        const ids = rows.rows.map((r) => r.id);
        expect(ids).toContain(userMsg.id);
        expect(ids).not.toContain(asstMsg.id);
        expect(ids).not.toContain(strayMsg.id);

        // A brand-new assistant row with the regenerated content was appended.
        const newAssistantRow = rows.rows.find(
          (r) => r.role === 'assistant' && r.content === 'You still have no apps.',
        );
        expect(newAssistantRow).toBeTruthy();
      } finally {
        await app.close();
      }
    });

    it('edit-and-resend: deletes from the user message and streams a turn with the new content', async () => {
      const app = await buildApp(USER_A, pool);

      try {
        const convR = await app.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-j-edit-resend', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();
        const conversationId = conversation.id;

        const userMsg = await appendMessage(pool, conversationId, {
          role: 'user',
          content: 'original question',
          toolCallId: null,
          toolName: null,
          toolArgs: null,
          toolResult: null,
        });
        await appendMessage(pool, conversationId, {
          role: 'assistant',
          content: 'original answer',
          toolCallId: null,
          toolName: null,
          toolArgs: null,
          toolResult: null,
        });

        global.fetch = vi.fn().mockResolvedValueOnce(
          gatewayResponse([
            { choices: [{ delta: { content: 'edited answer' }, finish_reason: null }] },
            { choices: [{ delta: {}, finish_reason: 'stop' }] },
          ]),
        );

        const regenR = await app.inject({
          method: 'POST',
          url: `/conversations/${conversationId}/regenerate`,
          payload: { message_id: userMsg.id, new_user_message: 'edited question' },
          headers: { authorization: 'Bearer test-jwt' },
        });

        expect(regenR.statusCode).toBe(200);
        const frames = parseSseFrames(regenR.body);
        expect(frames[frames.length - 1]).toMatchObject({ type: 'done' });

        const rows = await pool.query<{ role: string; content: string }>(
          `SELECT role, content FROM dashboard_agent_messages
           WHERE conversation_id = $1 ORDER BY created_at ASC`,
          [conversationId],
        );

        // Original user + assistant rows are gone; replaced by the new turn.
        expect(rows.rows.some((r) => r.content === 'original question')).toBe(false);
        expect(rows.rows.some((r) => r.content === 'original answer')).toBe(false);
        expect(rows.rows[0]).toMatchObject({ role: 'user', content: 'edited question' });
        expect(rows.rows.some((r) => r.role === 'assistant' && r.content === 'edited answer')).toBe(true);
      } finally {
        await app.close();
      }
    });

    it('rejects an ambiguous/invalid message_id with 400', async () => {
      const app = await buildApp(USER_A, pool);

      try {
        const convR = await app.inject({
          method: 'POST',
          url: '/conversations',
          payload: { title: 'e2e-case-j-invalid', model: 'gpt-4o' },
        });
        const { conversation } = convR.json<{ conversation: { id: string } }>();
        const conversationId = conversation.id;

        const userMsg = await appendMessage(pool, conversationId, {
          role: 'user',
          content: 'hi',
          toolCallId: null,
          toolName: null,
          toolArgs: null,
          toolResult: null,
        });

        // Regenerate (no new_user_message) but message_id points at a USER row — invalid.
        const regenR = await app.inject({
          method: 'POST',
          url: `/conversations/${conversationId}/regenerate`,
          payload: { message_id: userMsg.id },
          headers: { authorization: 'Bearer test-jwt' },
        });
        expect(regenR.statusCode).toBe(400);

        const asstMsg = await appendMessage(pool, conversationId, {
          role: 'assistant',
          content: 'hello',
          toolCallId: null,
          toolName: null,
          toolArgs: null,
          toolResult: null,
        });

        // Edit-and-resend (new_user_message set) but message_id points at an
        // ASSISTANT row — invalid.
        const editR = await app.inject({
          method: 'POST',
          url: `/conversations/${conversationId}/regenerate`,
          payload: { message_id: asstMsg.id, new_user_message: 'new text' },
          headers: { authorization: 'Bearer test-jwt' },
        });
        expect(editR.statusCode).toBe(400);

        // A totally unknown message_id also 400s (not found under a 404 path
        // here — validated the same way malformed input would be).
        const missingR = await app.inject({
          method: 'POST',
          url: `/conversations/${conversationId}/regenerate`,
          payload: { message_id: randomUUID() },
          headers: { authorization: 'Bearer test-jwt' },
        });
        expect(missingR.statusCode).toBe(404);
      } finally {
        await app.close();
      }
    });
  });
});
