#!/usr/bin/env bash
# Refresh every file in this folder from the live Butterbase platform.
# Reads BUTTERBASE_API_KEY from ../.env (or the environment).
# Run from the repo root or from inside `backend/` — both work.
#
# Functions are enumerated dynamically from the live app. Local function
# folders that don't exist on live are deleted. function.json mirrors the
# shape returned by the API (triggers array, agent_tool fields, etc.).
# rls/policies.sql is regenerated from rls/policies.json (qual + with_check
# from the /rls endpoint reconstruct each CREATE POLICY).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if [ -z "${BUTTERBASE_API_KEY:-}" ] && [ -f "../.env" ]; then
  set -a; . ../.env; set +a
fi
: "${BUTTERBASE_API_KEY:?set BUTTERBASE_API_KEY in ../.env or in the environment}"
: "${BUTTERBASE_APP_ID:=app_44zjayftl7b3}"
: "${BUTTERBASE_API_URL:=https://api.butterbase.ai/v1/$BUTTERBASE_APP_ID}"

H=(-H "Authorization: Bearer $BUTTERBASE_API_KEY" -H "Accept: application/json")

echo "→ schema"
curl -sS "${H[@]}" "$BUTTERBASE_API_URL/schema" | jq '.schema' > schema.json

echo "→ rls"
mkdir -p rls
curl -sS "${H[@]}" "$BUTTERBASE_API_URL/rls" | jq '.' > rls/policies.json

# Regenerate policies.sql from the JSON. The /rls endpoint returns qual (USING
# clause) and with_check (WITH CHECK clause) as raw SQL, so a clean
# CREATE POLICY can be reconstructed for every row. Service-bypass policies
# (role butterbase_service, qual true, with_check true) are omitted for
# readability; ALTER TABLE ... ENABLE RLS is emitted once per table.
{
  echo "-- =============================================================================="
  echo "-- RLS POLICIES — generated by backend/sync.sh from policies.json"
  echo "-- Live snapshot at $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not hand-edit."
  echo "-- Source of truth is the Butterbase platform (manage_rls / butterbase rls list)."
  echo "-- The *_service_bypass PERMISSIVE ALL policies on every table are omitted here."
  echo "-- =============================================================================="
  echo
  jq -r '
    .policies
    | map(select(.policyname | endswith("_service_bypass") | not))
    | sort_by(.tablename, .cmd, .policyname)
    | group_by(.tablename)
    | map(
        "-- \(.[0].tablename) " + ("-" * (74 - (.[0].tablename | length))) + "\n" +
        "ALTER TABLE \(.[0].tablename) ENABLE ROW LEVEL SECURITY;\n\n" +
        (map(
          "CREATE POLICY \(.policyname) ON \(.tablename) " +
          (if .permissive == "RESTRICTIVE" then "AS RESTRICTIVE " else "" end) +
          "FOR \(.cmd) " +
          "TO " + ((.roles | gsub("[{}]"; "") | split(",")) | join(", ")) +
          (if .qual != null and .qual != "" then "\n  USING (\(.qual))" else "" end) +
          (if .with_check != null and .with_check != "" then "\n  WITH CHECK (\(.with_check))" else "" end) +
          ";"
        ) | join("\n\n"))
      )
    | join("\n\n")
  ' rls/policies.json
  echo
} > rls/policies.sql

echo "→ functions (enumerate live)"
mkdir -p functions
FN_LIST_JSON="$(mktemp -t bbcrm_fns.XXXXXX)"
trap 'rm -f "$FN_LIST_JSON"' EXIT
curl -sS "${H[@]}" "$BUTTERBASE_API_URL/functions" > "$FN_LIST_JSON"
LIVE_NAMES="$(jq -r '.functions[].name' "$FN_LIST_JSON" | sort)"
if [ -z "$LIVE_NAMES" ]; then
  echo "  ✗ no functions returned from $BUTTERBASE_API_URL/functions — refusing to wipe local copy"
  exit 1
fi

echo "  live functions: $(echo "$LIVE_NAMES" | wc -l | tr -d ' ')"

for dir in functions/*/; do
  [ -d "$dir" ] || continue
  name="$(basename "$dir")"
  if ! grep -qx "$name" <<< "$LIVE_NAMES"; then
    echo "  - pruning local-only: $name"
    rm -rf "$dir"
  fi
done

while IFS= read -r name; do
  [ -n "$name" ] || continue
  payload="$(mktemp -t "bbcrm_fn.XXXXXX")"
  curl -sS "${H[@]}" "$BUTTERBASE_API_URL/functions/$name" > "$payload"

  code_len=$(jq -r '.code // "" | length' "$payload")
  if [ "$code_len" = "0" ] || [ "$code_len" = "null" ]; then
    echo "  ✗ $name: empty .code in response — bailing"
    jq '.' "$payload" | head -40
    rm -f "$payload"
    exit 1
  fi

  mkdir -p "functions/$name"
  jq -r '.code' "$payload" > "functions/$name/handler.ts"
  jq '{
        name,
        description,
        triggers,
        timeoutMs,
        memoryLimitMb,
        deployedAt,
        agent_tool,
        agent_tool_description,
        agent_tool_mode,
        agent_tool_exposed_to
      }' "$payload" > "functions/$name/function.json"
  rm -f "$payload"
  echo "  ✓ $name"
done <<< "$LIVE_NAMES"

echo "→ auth/config"
mkdir -p auth
{
  echo "{"
  echo "  \"_source\": \"manage_auth_config + manage_oauth (live $(date -u +%Y-%m-%d))\","
  echo "  \"oauth_providers\": "
  curl -sS "${H[@]}" "$BUTTERBASE_API_URL/auth/oauth-config" | jq '.configs | map({provider, client_id, client_secret: "<redacted>", redirect_uris, scopes, enabled})'
  echo "}"
} > auth/config.json
echo "  (jwt TTLs + password rules are tracked manually — refresh via dashboard or update_jwt)"

echo "→ integrations"
mkdir -p integrations
curl -sS "${H[@]}" "$BUTTERBASE_API_URL/integrations/config" | jq '.' > integrations/integrations.json

echo "→ storage"
# Storage uses a root-level endpoint, not /v1/<app_id>/... — and there is no
# /storage/config: publicReadEnabled is MCP-only. We snapshot the object
# inventory instead. BUTTERBASE_API_URL has the /v1/<app_id> suffix baked in,
# so derive the root from BUTTERBASE_API_URL by stripping that tail.
mkdir -p storage
BUTTERBASE_API_ROOT="${BUTTERBASE_API_URL%/v1/*}"
curl -sS "${H[@]}" "$BUTTERBASE_API_ROOT/storage/$BUTTERBASE_APP_ID/objects" | jq '.' > storage/objects.json
rm -f storage.json

echo "→ realtime"
curl -sS "${H[@]}" "$BUTTERBASE_API_URL/realtime/config" | jq '.' > realtime.json

echo "→ ai"
curl -sS "${H[@]}" "$BUTTERBASE_API_URL/ai/config" | jq '.' > ai.json

echo "✓ done — review with: git diff backend/"
