-- ==============================================================================
-- RLS POLICIES — generated by backend/sync.sh from policies.json
-- Live snapshot at 2026-06-24T18:20:29Z. Do not hand-edit.
-- Source of truth is the Butterbase platform (manage_rls / butterbase rls list).
-- The *_service_bypass PERMISSIVE ALL policies on every table are omitted here.
-- ==============================================================================

-- activities ----------------------------------------------------------------
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;

CREATE POLICY team_member_all ON activities FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- agent_messages ------------------------------------------------------------
ALTER TABLE agent_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY team_member_select ON agent_messages FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- agent_proposals -----------------------------------------------------------
ALTER TABLE agent_proposals ENABLE ROW LEVEL SECURITY;

CREATE POLICY team_member_all ON agent_proposals FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- agent_threads -------------------------------------------------------------
ALTER TABLE agent_threads ENABLE ROW LEVEL SECURITY;

CREATE POLICY team_member_select ON agent_threads FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- app_allowlist -------------------------------------------------------------
ALTER TABLE app_allowlist ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_write ON app_allowlist FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY team_member_select ON app_allowlist FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- autonomy_settings ---------------------------------------------------------
ALTER TABLE autonomy_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_write ON autonomy_settings FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY team_member_select ON autonomy_settings FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- capability_config ---------------------------------------------------------
ALTER TABLE capability_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_write ON capability_config FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY team_member_select ON capability_config FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- diagnoses -----------------------------------------------------------------
ALTER TABLE diagnoses ENABLE ROW LEVEL SECURITY;

CREATE POLICY team_member_select ON diagnoses FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- docs_sources --------------------------------------------------------------
ALTER TABLE docs_sources ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_write ON docs_sources FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY team_member_select ON docs_sources FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- escalation_targets --------------------------------------------------------
ALTER TABLE escalation_targets ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_write ON escalation_targets FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY team_member_select ON escalation_targets FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- escalations ---------------------------------------------------------------
ALTER TABLE escalations ENABLE ROW LEVEL SECURITY;

CREATE POLICY team_member_select ON escalations FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- integration_state ---------------------------------------------------------
ALTER TABLE integration_state ENABLE ROW LEVEL SECURITY;

CREATE POLICY team_member_select ON integration_state FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- memberships ---------------------------------------------------------------
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;

CREATE POLICY delete_admin_or_self ON memberships FOR DELETE TO butterbase_user
  USING (((user_id = (current_user_id())::uuid) OR (EXISTS ( SELECT 1
   FROM memberships m2
  WHERE ((m2.user_id = (current_user_id())::uuid) AND (m2.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));

CREATE POLICY admin_insert ON memberships FOR INSERT TO butterbase_user
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships m2
  WHERE ((m2.user_id = (current_user_id())::uuid) AND (m2.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY team_member_select ON memberships FOR SELECT TO butterbase_user
  USING ((user_id = (current_user_id())::uuid));

CREATE POLICY admin_update ON memberships FOR UPDATE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships m2
  WHERE ((m2.user_id = (current_user_id())::uuid) AND (m2.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships m2
  WHERE ((m2.user_id = (current_user_id())::uuid) AND (m2.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

-- outbound_disclosure_violations --------------------------------------------
ALTER TABLE outbound_disclosure_violations ENABLE ROW LEVEL SECURITY;

CREATE POLICY team_member_select ON outbound_disclosure_violations FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- pattern_signals -----------------------------------------------------------
ALTER TABLE pattern_signals ENABLE ROW LEVEL SECURITY;

CREATE POLICY team_member_select ON pattern_signals FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- support_messages ----------------------------------------------------------
ALTER TABLE support_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY team_member_all ON support_messages FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- support_skill -------------------------------------------------------------
ALTER TABLE support_skill ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_write ON support_skill FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY team_member_select ON support_skill FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- support_tickets -----------------------------------------------------------
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY team_member_all ON support_tickets FOR ALL TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- team_integrations ---------------------------------------------------------
ALTER TABLE team_integrations ENABLE ROW LEVEL SECURITY;

CREATE POLICY self_or_admin_write ON team_integrations FOR ALL TO butterbase_user
  USING (((user_id = (current_user_id())::uuid) OR (EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text])))))))
  WITH CHECK (((user_id = (current_user_id())::uuid) OR (EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text])))))));

CREATE POLICY team_member_select ON team_integrations FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

-- widget_secrets ------------------------------------------------------------
ALTER TABLE widget_secrets ENABLE ROW LEVEL SECURITY;

CREATE POLICY admin_delete ON widget_secrets FOR DELETE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY admin_insert ON widget_secrets FOR INSERT TO butterbase_user
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

CREATE POLICY team_member_select ON widget_secrets FOR SELECT TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE (memberships.user_id = (current_user_id())::uuid))));

CREATE POLICY admin_update ON widget_secrets FOR UPDATE TO butterbase_user
  USING ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM memberships
  WHERE ((memberships.user_id = (current_user_id())::uuid) AND (memberships.role = ANY (ARRAY['owner'::text, 'admin'::text]))))));

