#!/usr/bin/env bash
# Pull every live resource from the dev clone (app_md5001nugpan) into backend/.
# Mirrors backend/sync.sh but targets the clone instead of the production app.
#
# Usage (from repo root):
#   ./dev/sync-clone.sh
#
# Reads BUTTERBASE_API_KEY from .env (must have access to the clone app).
# To target a different app, set BUTTERBASE_CLONE_APP_ID in the environment.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

if [ -f ".env" ]; then
  set -a; . .env; set +a
fi

APP_ID="${BUTTERBASE_CLONE_APP_ID:-app_md5001nugpan}"
API_KEY="${BUTTERBASE_CLONE_API_KEY:-${BUTTERBASE_API_KEY:-}}"
API_URL="https://api.butterbase.ai/v1/$APP_ID"

: "${API_KEY:?Set BUTTERBASE_API_KEY (or BUTTERBASE_CLONE_API_KEY) in .env}"

H=(-H "Authorization: Bearer $API_KEY" -H "Accept: application/json")

echo "→ Syncing from clone: $APP_ID"
echo

echo "→ schema"
curl -sS "${H[@]}" "$API_URL/schema" | jq '.schema' > backend/schema.json
echo "  ✓ backend/schema.json"

echo "→ rls"
mkdir -p backend/rls
curl -sS "${H[@]}" "$API_URL/rls" | jq '.' > backend/rls/policies.json
{
  echo "-- RLS POLICIES — generated by dev/sync-clone.sh"
  echo "-- Clone snapshot at $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not hand-edit."
  echo
  jq -r '
    .policies
    | map(select(.policyname | endswith("_service_bypass") | not))
    | sort_by(.tablename, .cmd, .policyname)
    | group_by(.tablename)
    | map(
        "-- \(.[0].tablename) " + ("-" * (74 - (.[0].tablename | length))) + "\n" +
        "ALTER TABLE \(.[0].tablename) ENABLE ROW LEVEL SECURITY;\n\n" +
        (map(
          "CREATE POLICY \(.policyname) ON \(.tablename) " +
          (if .permissive == "RESTRICTIVE" then "AS RESTRICTIVE " else "" end) +
          "FOR \(.cmd) " +
          "TO " + ((.roles | gsub("[{}]"; "") | split(",")) | join(", ")) +
          (if .qual != null and .qual != "" then "\n  USING (\(.qual))" else "" end) +
          (if .with_check != null and .with_check != "" then "\n  WITH CHECK (\(.with_check))" else "" end) +
          ";"
        ) | join("\n\n"))
      )
    | join("\n\n")
  ' backend/rls/policies.json
  echo
} > backend/rls/policies.sql
echo "  ✓ backend/rls/"

echo "→ functions"
mkdir -p backend/functions
FN_JSON="$(mktemp -t bbclone_fns.XXXXXX)"
trap 'rm -f "$FN_JSON"' EXIT
curl -sS "${H[@]}" "$API_URL/functions" > "$FN_JSON"
LIVE_NAMES="$(jq -r '.functions[].name' "$FN_JSON" | sort)"

if [ -z "$LIVE_NAMES" ]; then
  echo "  ✗ no functions returned — refusing to wipe local copy"
  exit 1
fi
echo "  live: $(echo "$LIVE_NAMES" | wc -l | tr -d ' ') functions"

for dir in backend/functions/*/; do
  [ -d "$dir" ] || continue
  name="$(basename "$dir")"
  if ! grep -qx "$name" <<< "$LIVE_NAMES"; then
    echo "  - removing local-only: $name"
    rm -rf "$dir"
  fi
done

while IFS= read -r name; do
  [ -n "$name" ] || continue
  payload="$(mktemp -t "bbclone_fn.XXXXXX")"
  curl -sS "${H[@]}" "$API_URL/functions/$name" > "$payload"
  code_len=$(jq -r '.code // "" | length' "$payload")
  if [ "$code_len" = "0" ] || [ "$code_len" = "null" ]; then
    echo "  ✗ $name: empty code — skipping"
    rm -f "$payload"
    continue
  fi
  mkdir -p "backend/functions/$name"
  jq -r '.code' "$payload" > "backend/functions/$name/handler.ts"
  jq '{name,description,triggers,timeoutMs,memoryLimitMb,deployedAt,agent_tool,agent_tool_description,agent_tool_mode,agent_tool_exposed_to}' \
    "$payload" > "backend/functions/$name/function.json"
  rm -f "$payload"
  echo "  ✓ $name"
done <<< "$LIVE_NAMES"

echo "→ auth/config"
mkdir -p backend/auth
{
  echo "{"
  echo "  \"_source\": \"clone sync $(date -u +%Y-%m-%d)\","
  echo "  \"oauth_providers\":"
  curl -sS "${H[@]}" "$API_URL/auth/oauth-config" \
    | jq '.configs | map({provider, client_id, client_secret: "<redacted>", redirect_uris, scopes, enabled})'
  echo "}"
} > backend/auth/config.json
echo "  ✓ backend/auth/config.json"

echo "→ integrations"
mkdir -p backend/integrations
curl -sS "${H[@]}" "$API_URL/integrations/config" | jq '.' > backend/integrations/integrations.json
echo "  ✓ backend/integrations/integrations.json"

echo "→ realtime"
curl -sS "${H[@]}" "$API_URL/realtime/config" | jq '.' > backend/realtime.json
echo "  ✓ backend/realtime.json"

echo "→ ai"
curl -sS "${H[@]}" "$API_URL/ai/config" | jq '.' > backend/ai.json
echo "  ✓ backend/ai.json"

echo
echo "✓ Clone sync complete — review: git diff backend/"
